### ISSUE TITLE
Support Profiler Attach for .NETCore 3

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/CLRInstrumentationEngine#106]
ICorProfiler attach has existed for a long time but it's only recently in dotnet Core 3 that module metadata emit and ReJit have been provided. 

https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/Profiler%20Attach%20on%20CoreCLR.md

https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/ReJIT%20on%20Attach.md

**Comment by WilliamXieMSFT** [comment]
In CoreClr, an application will only have one AppDomain and the concept of AppDomains is replaced with ALC (AssemblyLoadContexts).

**Comment by jander-msft** [comment]
I've closed this issue in favor of the more granular tasks and the project tracking them.
