### ISSUE TITLE
Turning on/off Application Insights in Azure App Service portal resets InstrumentationEngine_EXTENSION_VERSION to disabled

### ISSUE THREAD

**Issue by bobuva** [microsoft/CLRInstrumentationEngine#114]
### Environment
Azure App Service

### Scenario
I have a .NET profiler installed in the App Service, and have `InstrumentationEngine_EXTENSION_VERSION` set to `~1` in the Application settings, via the portal:

I enabled Application Insights via the portal (Deployment -> Application Insights). When I go back to look at the Application settings, InstrumentationEngine_EXTENSION_VERSION is reset to `disabled`. 

I noticed that it gets reset to `disabled` for any Application Insights feature I enable, and even when I disabled Application Insights, it reset it!

This is clearly a bug or at least not acceptable behavior because, with CLRIE, it's possible to have multiple profilers running. My workaround has been to manually check the InstrumentationEngine_EXTENSION_VERSION application setting and set it when necessary.

Reproducing this bug should be easy given the explanation above.

Although this is not necessarily a CLR Instrumentation Engine bug, I was advised that reporting it here was one way to get some movement on fixing it.

**Comment by jchli** [comment]
We're also seeing this behavior. At best, it is additional noise when we're inspecting our change history.

**Comment by WilliamXieMSFT** [comment]
Thanks for the feedback, I'll get in contact with the responsible teams who may be able to help address this.

**Comment by WilliamXieMSFT** [comment]
Update:

Unfortunately, the Application Insights portal experience won't make any changes to their current functionality which means we'll need to live with this degraded experience in the near future. The current workaround is as @bobuva mentioned - manually checking `InstrumentationEngine_EXTENSION_VERSION` is set. 

If there is enough push back to improve this experience, please reach out to `clrieowners@microsoft.com` to help us build a case.
