### ISSUE TITLE
CLRIE Roadmap link is 404

### ISSUE THREAD

**Issue by bobuva** [microsoft/CLRInstrumentationEngine#125]
The link to the CLRIE Roadmap in the `Overview` section of the repository's `README.md` goes to a 404. Knowing the roadmap for this project would be helpful for vendors and users of the instrumentation engine.

**Comment by WilliamXieMSFT** [comment]
Thanks for catching this, Bob! The filename is capitalized but the link is not.

**Comment by WilliamXieMSFT** [comment]
https://github.com/microsoft/CLRInstrumentationEngine/pull/126

**Comment by bobuva** [comment]
Fixed, closing.
