### ISSUE TITLE
InstrumentationEngine.ProfilerProxy_x(86|64).dll activation gets stuck on malformed version strings

### ISSUE THREAD

**Issue by sanikolov** [microsoft/CLRInstrumentationEngine#155]
Consider the following folder structure which contains the malformed version string 1.99
```
snikolov@DESKTOP-5UO7643:/mnt/c/Program Files/Microsoft CLR Instrumentation Engine$ find
. -type f

./1.99/Instrumentation32/MicrosoftInstrumentationEngine_x86.dll
./1.99/Instrumentation64/MicrosoftInstrumentationEngine_x64.dll
./Proxy/v1/InstrumentationEngine.ProfilerProxy_x64.dll
./Proxy/v1/InstrumentationEngine.ProfilerProxy_x86.dll
```

Observed behavior - on activation the profiler proxy becomes permanently stuck.
Expected behavior - the profiler proxy shall exit with an error code and print a message either on stdout/stderr or the file pointed to by MicrosoftInstrumentationEngine_FileLogPath.

Rename folder 1.99 to something more sensible like 1.0.28 and observe that now the profiler proxy works as designed.

**Comment by WilliamXieMSFT** [comment]
This issue arises when there is no valid folder as latest. `while (FindNextFile(hSearchHandle, &findFileData))` will continue returning true despite no more folders/files to find.

**Comment by WilliamXieMSFT** [comment]
Regarding Expected behavior, the ProfilerProxy currently only writes to the eventlog and does not support the FileLog.

Regarding failure - `CCriticalSectionHolder holder(&m_cs);` appears to be dead-locked with the same issue that plagued CLRIE in the past. Fix is to not call ShutDown() in the ~CEventLogger().
