### ISSUE TITLE
GetILFunctionBody supports NULL for ULONG* pcbMethodSize

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/CLRInstrumentationEngine#186]
https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method

Despite the annotation, pcbMethodSize can be NULL when querying from the CLR. However, CLRIE assumes this is not null (via SAL) but does not null-check and `*pcbMethodSize = 0;` in `CCorProfilerInforWrapper::GetILFunctionBody()` encounters an Access Violation (AV) with nullptr.

**Comment by WilliamXieMSFT** [comment]
For Example: https://github.com/microsoft/clr-samples/blob/master/ProfilingAPI/ReJITEnterLeaveHooks/ILRewriter.cpp#L208 passes in NULL to GetILFunctionBody which works for .NET Framework and .NET Core but fails with CLRIE

**Comment by WilliamXieMSFT** [comment]
https://github.com/dotnet/runtime/blob/5ef367a888fa8a25ce157cf340bd271efd36c72f/src/coreclr/src/vm/proftoeeinterfaceimpl.cpp#L4412

Despite its own SAL annotation, the CLR conducts a NULL check.

**Comment by delmyers** [comment]
What is the bug here? It seems that at most, we should be doing an IfNullRet on the pcbMethodSize, and not depend on a side-effect of a bug in the clr profiler apis. This seems like a bug in the CLR. It is either:

1. A bug in the SAL or
2. A bug in the implementation and 
    1. A bug in the sample provided by the CLR

**Comment by WilliamXieMSFT** [comment]
I agree, it looks like a bug in the CLR that allows behavior despite its own contract via the annotation. I'll open an issue on the CLR and close this issue.

As an aside, I'm worried that profiler authors will depend on these accidental behaviors and encounter issues when connecting to the CLRIE RawProfilerHook.

**Comment by delmyers** [comment]
I would be OK with putting an IfNullRet in our code, so that we are explicit about the error. That way we return a null argument error, rather than throwing an exception.

**Comment by WilliamXieMSFT** [comment]
https://github.com/dotnet/runtime/issues/1281

I'll submit a PR to address this for CLRIE.

**Comment by WilliamXieMSFT** [comment]
Found the corresponding doc in coreclr: https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/Documentation/botr/profiling.md#optional-out-parameters
