### ISSUE TITLE
ProductionBreakpoints_x64.config not found on linux

### ISSUE THREAD

**Issue by sanikolov** [microsoft/CLRInstrumentationEngine#210]
In branch develop, commit ID 337cc8f447ffdc41b6f8d8cc3faebb97ab816621 I was able to build
`CLRInstrumentationEngine/out/Linux/bin/x64.Debug/ClrInstrumentationEngine/libInstrumentationEngine.so`
successfully by running build.sh .
However, when I attempt to activate the profiler I get this error

```
LogError[17:53:54]:Invalid configuration file.
LogError[17:53:54]:Failed to load configuration file '/home/snikolov/CLRInstrumentationEngine/out/Linux/bin/x64.Debug/ClrInstrumentationEngine/ProductionBreakpoints_x64.config'.
```

When I searched for ProductionBreakpoints_x64.config among the build artifacts, it was not found.
If the linux build is too difficult to do correctly by external developers plz provide a binary package for download that has all the right pieces in it.

**Comment by WilliamXieMSFT** [comment]
@sanikolov Thanks for trying out Linux build! Unfortunately it's not ready for external parties yet and we are just hard-coding our internal Instrumentation Method. 

Here is the task to generalize it: https://github.com/microsoft/CLRInstrumentationEngine/issues/60

**Comment by sanikolov** [comment]
Actually, I am not just trying it out.
My project is due ASAP and that includes linux which I left for last.
If you could provide a 1 off correct linux build that I could download that would be hugely beneficial since I've missed deadlines and estimates repeatedly while working on getting onboarded with CLRIE.

**Comment by WilliamXieMSFT** [comment]
@sanikolov To quickly get unblocked, you can modify https://github.com/microsoft/CLRInstrumentationEngine/blob/337cc8f447ffdc41b6f8d8cc3faebb97ab816621/src/ExtensionsHostLib/CExtensionsHost.cpp#L164 with your InstrumentationMethod configuration instead of ProductionBreakpoints and build locally for all of the binaries needed.

**Comment by sanikolov** [comment]
Thanks for the clarification.
For those who read this page later and feel as confused as I was, the explanation is that the config file shown above (e.g. ProductionBreakpoints_x86.config) has the same format as the file pointed to by `MicrosoftInstrumentationEngine_ConfigPath64_<whatever>`  and serves the same purpose (i.e. to declare the guid and a relative path to the shared lib).
It appears that the env variable `MicrosoftInstrumentationEngine_ConfigPath64_<whatever>` is not acted on by CLRIE on linux, instead values must come from a file such as ProductionBreakpoints_x86.config
