### ISSUE TITLE
Raw Profiler Hook bug with New Relic - Events are not appearing back on the dashboard

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/CLRInstrumentationEngine#226]
The NewRelic profiler returns S_OK upon Initialize, however it looks like the NewRelic agent doesn't appear to be launched.

**Comment by WilliamXieMSFT** [comment]
I've reached out to developers from NewRelic with instructions for patching CLRIE and hooking up NewRelic to CLRIE's RawProfilerHook.

**Comment by WilliamXieMSFT** [comment]
It appears the underlying issue is caused by a limitation on CLRIE around ReJIT. Engineers from NewRelic are looking into fixing their profiler around this limitation.

**Comment by alanwest** [comment]
@WilliamXieMSFT I believe this issue has been resolved in our latest release - version 8.30.0. I have reworked things so that `SetILFunctionBody` is invoked upon `GetReJITParameters` rather than `ReJITCompilationStarted`.

**Comment by WilliamXieMSFT** [comment]
@alanwest Awesome, thank you for letting me know. I'll run a quick validation on our side as well and will close this issue once that's completed.

**Comment by WilliamXieMSFT** [comment]
Confirmed 👍 

![image](https://user-images.githubusercontent.com/29215642/89464317-1b4cc800-d725-11ea-8861-ff48a2a34c7b.png)

**Comment by sanikolov** [comment]
@WilliamXieMSFT what onboarded profiler did you use to verify compatibility with New Relic?
In my tests New Relic 8.31 is not compatible with our onboarded profiler under IIS, .NET framework 4.0
On your end I'd recommend the Application Insights onboarded profiler for compatibility testing with 3rd party APM since it is large and non trivial.

**Comment by WilliamXieMSFT** [comment]
@sanikolov I verified against NewRelic 8.30, I can try updating and seeing if there were any changes.

**Comment by sanikolov** [comment]
I take my comment back. Certain protect mode operations were blocking metrics from reaching the dashboard. No reason to reopen this task.
