### ISSUE TITLE
Attach: Configuration source settings can describe that relative path should be prepended

### ISSUE THREAD

**Issue by jander-msft** [microsoft/CLRInstrumentationEngine#227]
Need to allow the individual settings of a configuration source to specify that the directory of the configuration sources file should be prefixed to the setting value (thus the value is interpreted as a relative path) before serializing into the engine configuration.

**Comment by WilliamXieMSFT** [comment]
"path\to\configsource.xml"
```
      <Platform Chip="x86" Path="Instrumentation32\ProductionBreakpoints_x86.config" />
```

Resolves to "path\to\Instrumentation32\ProductionBreakpoints_x86.config"

**Comment by WilliamXieMSFT** [comment]
Absolute paths are also detected and won't be modified.
