### ISSUE TITLE
CProfilerManager::AssemblyLoadFinished Should Check If Assembly Was Already Created Before Creating New Instance

### ISSUE THREAD

**Issue by m0nkey653** [microsoft/CLRInstrumentationEngine#279]
`ConstructAssemblyInfo` is called in both `ConstructModuleInfo` and `AssemblyLoadFinished`. This makes sense, because in most cases,  `ICorProfilerCallback::AssemblyLoadFinished` occurs after `ICorProfilerCallback::ModuleLoadFinished`.

The code in `ConstructModuleInfo` checks to see if an assembly with the same ID is loaded before constructing a new `AssemblyInfo` and adding it to the appropriate AppDomain. This instance `AssemblyInfo` is also added to the current `ModuleInfo`.

`AssemblyLoadFinished` does not check if an instance of this `AssemblyInfo` already exists and creates a new instance and replaces the previous instance in the `AppDomainInfo` assembly collection.

The module collection will only get updated in the `AssemblyInfo` that is referenced in the `ModuleInfo`, the instance that is now stored in the `AppDomainInfo` won't have the module.

Another problem with have two instances is when an InstrumentationMethod uses the container interface. They won't have the same container in both cases.

A possible fix is in PR - #278

**Comment by WilliamXieMSFT** [comment]
The current PR fix looks fine, however quoting @wiktork - "see if there’s a singular place in the module/assembly load lifetime we should pick to construct these, rather than construct them on in both callbacks and verify whether they exist already or not."

**Comment by m0nkey653** [comment]
@WilliamXieMSFT - I agree. It seems like all cases of AssemblyLoadFinished should find that the `CAssemblyInfo` was already created in the first `ModuleLoadFinished` for that assembly. So, could the code in `AssemblyLoadFinished` just pull the assembly from the AppDomain's collection and return an error if one wasn't found?

**Comment by WilliamXieMSFT** [comment]
Just a clarification: during ICorProfilerCallback:ModuleAttachedToAssembly, CLRIE actually lies to InstrumentationMethods by raising IInstrumentationMethod::OnModuleLoaded. CLRIE doesn't raise any InstrumentationMethod event during ICorProfilerCallback::ModuleLoadFinished.

@m0nkey653 I'm not sure if there are scenarios where AssemblyInfo is available during AssemblyLoadFinished but not during ModuleAttachedToAssembly, potentially returning an error would be bad in that case.
