### ISSUE TITLE
standalone method infos are not configured properly for instrumentation

### ISSUE THREAD

**Issue by jakubch1** [microsoft/CLRInstrumentationEngine#323]
Our code coverage instrumentation method is fetching instructions for all methods during OnModuleLoad. 
This causes that CLR IE logs are full of (for example 80k such lines):

....
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
LogError[07:46:41]:CMethodInfo::GetInstructions - standalone method infos are not configured properly for instrumentation.
....

Can we somehow avoid it? Can this be changed to warning?

**Comment by delmyers** [comment]
This is reasonable. If an instrumentation engine wants to inspect the IL of a method that will never be jitted, there is no other way for them to do this. It isn't really an error. We should probably not log it.

@wiktork @jander-msft do you have any other opinions?

**Comment by delmyers** [comment]
@jakubch1 feel free to submit a PR on this one.

**Comment by wiktork** [comment]
Did we want to track the instruction graph as immutable in those situations?
