### ISSUE TITLE
The difference between BeforeInstrumentMethod & InstrumentMethod

### ISSUE THREAD

**Issue by robertpi** [microsoft/CLRInstrumentationEngine#346]
Hello all,

I'm unclear on the difference between `BeforeInstrumentMethod`, `InstrumentMethod`. It seems both are called if `ShouldInstrumentMethod` sets pbInstrument to true, the signatures are the same and both can be used for rewriting methods. So, it's unclear which I used use for my rewrites. I noticed the "Nagler" example /  test uses both to preform different kinds of instrumentation, but it's unclear why it does this.

Also, is this the correct forum for design questions? I'll probably have some more questions.

Thanks,
Robert

**Comment by wiktork** [comment]
The recommended way to instrument is to use `InstrumentMethod`. `BeforeInstrumentMethod` is used for whole method body replacement. In this scenario, one InstrumentationMethod will replace the entire method body (along with new IL offset maps) while other instrumentation methods will make incremental changes. See https://github.com/microsoft/CLRInstrumentationEngine/blob/d976f4729dfa7d070324f5cbc8f8ba4d26c025a0/src/InstrumentationEngine.Api/InstrumentationEngine.idl#L277-L282 and https://github.com/microsoft/CLRInstrumentationEngine/blob/d976f4729dfa7d070324f5cbc8f8ba4d26c025a0/src/InstrumentationEngine.Api/InstrumentationEngine.idl#L602-L612

Please feel free to post more questions in this repo.

**Comment by robertpi** [comment]
Thanks, that's really helpful!
