### ISSUE TITLE
Configuration Variables are Case Sensitive

### ISSUE THREAD

**Issue by plnelson** [microsoft/CLRInstrumentationEngine#348]
CLRInstrumentationEngine Doesn't recognize configuration unless casing is exact.  For example `MicrosoftInstrumentationEngine_ConfigPath64_*` is recognized.  In contrast `microsoftinstrumentationengine_configpath64_*`.  is _not_ recognized.  The CLR is case insensitive for variables such as `COR_ENABLE_PROFILING` so CLRInstrumentationEngine should be as well.

This is causing an issue for me because the IISExpress launcher is changing environment variables to lower case blocking dynamic instrumentation profiling of ASP.NET applications.  Rather than fix that code, it seems more appropriate to make the CLRInstrumentationEngine config case insensitive.

**Comment by wiktork** [comment]
It looks like we are inconsistent with how we process environment variable names:
- Most go through `GetEnvironmentVariable`, and are case insensitive
- Some have explicit checks, like `MicrosoftInstrumentationEngine_ConfigPath64_` mentioned above so they end up case sensitive.
- We should also consider whether we care about the case sensitivity for values. For example, `MicrosoftInstrumentationEngine_LogLevel` and `MicrosoftInstrumentationEngine_FileLog` have case sensitive values.

**Comment by plnelson** [comment]
I was planning to leave the values case sensitive - as well as leave the names case sensitive on Unix.  IMO, the log path should be case sensitive.  If we want to be case insensitive about the meaning of log level, that is a different issue to consider.

**Comment by wiktork** [comment]
> I was planning to leave the values case sensitive - as well as leave the names case sensitive on Unix. IMO, the log path should be case sensitive. If we want to be case insensitive about the meaning of log level, that is a different issue to consider.

Sounds good. 

> Most go through GetEnvironmentVariable, and are case insensitive

This is for Windows only, GetEnvironmentVariable is case sensitive for Unix.
