### ISSUE TITLE
Build NaglerInstrumentationMethod on Linux

### ISSUE THREAD

**Issue by delmyers** [microsoft/CLRInstrumentationEngine#361]

**Comment by delmyers** [comment]
depends on #360 #359 #358 and #357

**Comment by oakcode** [comment]
Hi all, any news here? I am very keen on to try CLRIE on Linux (I already did it on Windows) but I do not know how to do that without NaglerInstrumentationMethod on Linux. Ok, CLRIE is stared on Linux but how I do not have built plugin for CLRIE further testing is impossible.
Are you planning to enable build on Linux soon? Also, if you are open to contributing maybe I can help somehow but probably I will need some information from you first.

Thanks.
All the best

**Comment by delmyers** [comment]
@oakcode There is currently a PR out to get the build portion working. It isn't perfect, because it still has a dependency on a common library, but it is a start. 

Also, we don't have any code that actually exercises the Nagler profiler on Linux, so we don't know for sure whether it works. But, the code that is in the PR #523 should be a good starting point for you.

**Comment by oakcode** [comment]
Hi @delmyers, thanks

I have created empty plugin for CLR IE, just for test, and now it does not look good. Really simple plugin cannot be loaded on linux, so I have to fix it first. But, Nagler is definitely something what I need at the end because it contains many useful examples. 

Thanks again, all the best

**Comment by delmyers** [comment]
@oakcode 

After the PR goes through, the header files in src/unix/inc/mincom and src/unix/inc/mincor will help you a lot to get off the ground. They contain the header files that define the layouts for many CLR/COM types that you need to get started with building instrumentation methods, without needing to get the whole windows SDK

**Comment by WilliamXieMSFT** [comment]
@oakcode #524 may also be a resource for you in building on Linux. 

If you would like to contribute fixes or updates, feel free to fork the repo or open new issues. Thank you for your interest in using CLRIE and please continue reaching out if you have any further questions or suggestions.

**Comment by oakcode** [comment]
Thank you @delmyers and @WilliamXieMSFT 🥇 
You have helped me a lot. I have changed Nagler on the way I needed and now everything works fine on Linux. 
Thank you once again and I hope that I will be able to contribute soon.

**Comment by delmyers** [comment]
@oakcode, glad to help!
