### ISSUE TITLE
Version 1.0.41 is broken on linux

### ISSUE THREAD

**Issue by jakubch1** [microsoft/CLRInstrumentationEngine#426]
jakubch@Jachocho-5820:~/vscodecoverage/artifacts/test/Microsoft.CodeCoverage/InstrumentationEngine/ubuntu/x64$ ldd -r libInstrumentationEngine.so
        linux-vdso.so.1 (0x00007ffe61bb8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff5574d2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff5572b3000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff556f2a000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007ff556b69000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007ff556962000)
        libunwind-x86_64.so.8 => /usr/lib/x86_64-linux-gnu/libunwind-x86_64.so.8 (0x00007ff556743000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff5563a5000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff55618d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff555d9c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff557ada000)
        libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007ff5559e4000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff5557c7000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007ff5555a1000)
        libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007ff555386000)
        libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007ff5537dd000)
undefined symbol: PathCanonicalizeW     (./libInstrumentationEngine.so)
undefined symbol: PathAppendW   (./libInstrumentationEngine.so)

Symbols PathCanonicalizeW  and PathAppendW  are not available in linux. Could you please add validation to your linux pipelines to run `ldd -r libInstrumentationEngine.so` and check if there are no issues?

**Comment by jander-msft** [comment]
cc @WilliamXieMSFT

**Comment by delmyers** [comment]
Thanks, Jakub for finding this. 

Maybe we should just abandon the PAL path libraries for this, and use individual OS functions?

**Comment by WilliamXieMSFT** [comment]
Thanks Jakub for catching this, and +1 to adding more validations on Linux.

**Comment by WilliamXieMSFT** [comment]
https://github.com/microsoft/CLRInstrumentationEngine/pull/427
