### ISSUE TITLE
make CLRIE builds possible on Alpine linux

### ISSUE THREAD

**Issue by sanikolov** [microsoft/CLRInstrumentationEngine#450]
This is a market driven requirement.
The following odd image + clang combination may prove useful to get you there quicker.

```
docker pull alpine:3.11      # min version where .net5.0 is supported by MSFT
apk add --no-cache bash sudo openssl xz git make musl-dev ca-certificates g++ wget
# manually add (append)   http://dl-cdn.alpinelinux.org/alpine/v3.6/main   to /etc/apk/repositories
apk add 'clang=4.0.0-r0'
```

**Comment by jander-msft** [comment]
CLRIE is already built on Alpine using an image built from the following Docker file: https://github.com/microsoft/CLRInstrumentationEngine/blob/main/src/unix/docker/dockerfiles/build/alpine/Dockerfile

**Comment by delmyers** [comment]
I tried this locally recently, and I think that the base image that we are using for that docker file no longer exists.

**Comment by jander-msft** [comment]
> I tried this locally recently, and I think that the base image that we are using for that docker file no longer exists.

Yup, those were deleted. See https://github.com/dotnet/dotnet-docker/issues/2848

We just need to choose an appropriate base image from https://mcr.microsoft.com/v2/dotnet-buildtools/prereqs/tags/list, but probably something that is still maintained from this manifest: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/manifest.json

Or we can build our own with minimal dependencies and not have to use an arbitrary base image from the dotnet-buildtools/prereqs repo.

**Comment by sanikolov** [comment]
Any alternatives to https://proddiagbuild.azurecr.io/v2/clrie-build-alpine/manifests/latest?

```
docker run --name clrie-build 
-v c:/tmp/CLRInstrumentationEngine/src:/root/ClrInstrumentationEngine/src:ro
-v c:/tmp/CLRInstrumentationEngine/tools:/root/ClrInstrumentationEngine/tools:ro
-v c:/tmp/CLRInstrumentationEngine/inc:/root/ClrInstrumentationEngine/inc:ro
-v c:/tmp/CLRInstrumentationEngine/build:/root/ClrInstrumentationEngine/build:ro 
--net=host proddiagbuild.azurecr.io/clrie-build-alpine:latest bash 
/root/ClrInstrumentationEngine/src/build.sh x64 Release clean
Unable to find image 'proddiagbuild.azurecr.io/clrie-build-alpine:latest' locally
docker: Error response from daemon: Head 
"https://proddiagbuild.azurecr.io/v2/clrie-build-alpine/manifests/latest": 
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.
```

Also
```
C:\tmp\CLRInstrumentationEngine\src\unix\docker\dockerfiles\build\alpine>docker build .
[+] Building 2.2s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 3.03kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/microsoft/dotnet-buildtools-prereqs:alpine-3.6-3148f11-201711190  2.0s
 => [auth] microsoft/dotnet-buildtools-prereqs:pull token for registry-1.docker.io                                 0.0s
------
 > [internal] load metadata for docker.io/microsoft/dotnet-buildtools-prereqs:alpine-3.6-3148f11-20171119021156:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, 
repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by sanikolov** [comment]
ping, plz post an update here if you have one

**Comment by sanikolov** [comment]
@WilliamXieMSFT 
Can you publish the CLRIE binaries for Alpine the same way you publish windows MSIs and merge modules?
Alternatively, if you can provide the Dockerfile definitions I can build these binaries myself.

**Comment by delmyers** [comment]
There is a docker file for building on alpine. It can be found in /src/unix/docker/dockerfiles/.

I just used this command to build a local image: cat /mnt/e/dd/CLRInstrumentationEngine/src/unix/docker/dockerfiles/alpine/Dockerfile | sudo docker build -t 'alpineclrie' -f - '/mnt/e/dd/CLRInstrumentationEngine
/src/unix/docker/context/'

(Note, the docker context is needed in order to pull in all of the additional prerequisites that we need).

From there, you should be able to create a container. Note, our build scripts are picky about where the clrie source lives. Mount your CLRIE repository root to /root/ClrInstrumentationEngine when creating the container.

I have not run a build on it yet, so I don't know if it will work. Good luck.

**Comment by sanikolov** [comment]
Thanks. Unfortunately I get

```
 => ERROR [internal] load metadata for docker.io/microsoft/dotnet-buildtools-prereqs:alpine-3.6-3148f11-20171119021156
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by jander-msft** [comment]
I think your branch is out of date. The Dockerfile at https://github.com/microsoft/CLRInstrumentationEngine/blob/main/src/unix/docker/dockerfiles/build/alpine/Dockerfile uses `mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-20211214164113-8a6f4f3`

**Comment by delmyers** [comment]
@sanikolov Looks like you are running on Windows with docker? I was able to get a musl build using this powershell command. Note: I am doing this in a box with WSL ubuntu + docker installed.

.\DockerLocalBuild.ps1 -CLib musl -BuildDockerImage -RebuildImage -Wsl
