### ISSUE TITLE
Host MSI/MSM Downloadable links

### ISSUE THREAD

**Issue by WilliamXieMSFT** [microsoft/CLRInstrumentationEngine#57]
Create downloadable links to released MSI/MSM files once available.

**Comment by sanikolov** [comment]
Neither getting_started.md nor build.md instructions worked for me. Can you provide downloadable links in the interim while license/UI issues are sorted out?

**Comment by jander-msft** [comment]
> Neither getting_started.md nor build.md instructions worked for me. Can you provide downloadable links in the interim while license/UI issues are sorted out?

Please open a new issue and specifically explain how "Neither getting_started.md nor build.md instructions worked for me." so that we can assist you.
